version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./netlify
      dockerfile: Dockerfile.backend
    ports:
      - "${BACKEND_PORT}:3001"
    volumes:
      - ./netlify/express-server.ts:/app/express-server.ts
      - ./netlify/.env:/app/.env
      - ./netlify/data:/app/data
      - ./netlify/services:/app/services
      - ./netlify/types:/app/types
      - ./netlify/dist:/app/dist
      - ./netlify/logs:/app/logs
    environment:
      # internal port 3001 is fixed above and in Dockerfile.backend, do not change
      - PORT=3001
    restart: unless-stopped
    #network_mode: "host"
    networks:
      - app-network

  mariadb:
    container_name: mariadb
    image: "mariadb:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3366:3306"
    # preserve data volume
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - app-network

#volumes:
#  mariadb_data:
#     driver: local
networks:
  app-network:
    driver: bridge