#FROM arm64v8/node:18
FROM node:18-alpine

WORKDIR /app

# Print architecture information for debugging
RUN uname -a && \
    node -p "process.arch" && \
    node -p "os.arch()"

COPY package*.json ./

RUN npm install --legacy-peer-deps

# Copy source files
COPY . .

# Build TypeScript
RUN npm run build

EXPOSE 3001

CMD ["npm", "run", "dev"]
